### ISSUE TITLE
Checklist to publishing first version

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#3]
@mcollina @addaleax ... please update this with whatever additional items you think are needed.

Things to do before publishing version 1:

* [x] Completed Tests
  * [x] 100% Code Coverage - https://github.com/jasnell/piscina/pull/6 - CI is currently failing due to < 100 coverage
  * [x] Green CI on all platforms - https://github.com/jasnell/piscina/pull/6
* [ ] Docs
  * [x] Full API doc
  * [ ] Design explanation
  * [ ] Getting started
* [ ] Examples
* [ ] Benchmarks
* [x] Contributing guide
* [x] Code of conduct file - https://github.com/jasnell/piscina/pull/4
* [x] Email to NearForm explaining project and intent
* [ ] Blog post (for Clinic.js or NearForm blogs)
* [ ] Introductory video (introduce project, how to use it, what it's for)
* [ ] npm publish - I've published an empty placeholder to npm currently at version 1.0.0-pre. Once we're ready to flip the switch, any of the three of us should be able to publish the actual module.

Couple of questions: 

1. Where should piscina live? Is having it in my personal github sufficient for now or should we move it somewhere more general?

2. @mcollina, is there a fastify integration angle here? e.g. any way that a fastify-piscina type plugin makes sense? Is there a graphql angle?

3. Should we also export an ESM version?

**Comment by addaleax** [comment]
> Should we also export an ESM version?

I’ve been meaning to do that :) I think with having an `exports:` key from the beginning we should be fine here. The only thing I wanted investigate more is whether typescript already supports generating ESM wrappers: If they currently don’t, they definitely should start doing so. Either way, I’m on that. :)

**Comment by mcollina** [comment]
I would have already released. The plan for 1.0.0 is ok. I would add some internal stats tracking, something that answer to the question of “is this healthy?” - it would be useful for healthcheck, prometheus integration etc.

Regarding fastify integrations, it would be interesting to do a PoC where the route handlers are executed in workers. Another very interesting option would be to check if React SSR could be run off the main thread.

**Comment by jasnell** [comment]
I'll do a release on version 1.0.0 on this today. @mcollina, how do you recommend we handle publishing to npm

**Comment by mcollina** [comment]
Manual, you need 2FA.
